In [41]:
import pandas as pd
import re

In [50]:
pattern = r'\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}'  
date=[]
time=[]
with open('regex.csv', 'r') as file:           
    text=file.read()
    li=re.findall(pattern,text)
    
    for i in li:
        date.append(i.split("T")[0])
        time.append(i.split("T")[1])
df = pd.read_csv('regex.csv')
df.drop(columns=["datetime"],inplace=True)
df["date"]=date
df["time"]=time
df.to_csv("Regex_New.csv",index=False)
df=pd.read_csv("Regex_New.csv")
df

    unitid  temp        date      time
0        1    38  2024-09-21  15:30:00
1        1    37  2024-09-21  15:31:00
2        1    39  2024-09-21  15:32:00
3        1    36  2024-09-21  15:33:00
4        1    40  2024-09-21  15:34:00
5        1    38  2024-09-21  15:35:00
6        1    39  2024-09-21  15:36:00
7        1    37  2024-09-21  15:37:00
8        1    36  2024-09-21  15:38:00
9        1    40  2024-09-21  15:39:00
10       2    36  2024-09-21  15:30:00
11       2    35  2024-09-21  15:31:00
12       2    40  2024-09-21  15:32:00
13       2    41  2024-09-21  15:33:00
14       2    36  2024-09-21  15:34:00
15       2    37  2024-09-21  15:35:00
16       2    39  2024-09-21  15:36:00
17       2    38  2024-09-21  15:37:00
18       2    34  2024-09-21  15:38:00
19       2    35  2024-09-21  15:39:00
20       3    41  2024-09-21  15:30:00
21       3    38  2024-09-21  15:31:00
22       3    39  2024-09-21  15:32:00
23       3    40  2024-09-21  15:33:00
24       3    37  2024-09-21  15:34:00
25       3    38  2024-09-21  15:35:00
26       3    41  2024-09-21  15:36:00
27       3    39  2024-09-21  15:37:00
28       3    42  2024-09-21  15:38:00
29       3    40  2024-09-21  15:39:00
30       4    37  2024-09-21  15:30:00
31       4    36  2024-09-21  15:31:00
32       4    38  2024-09-21  15:32:00
33       4    39  2024-09-21  15:33:00
34       4    40  2024-09-21  15:34:00
35       4    36  2024-09-21  15:35:00
36       4    37  2024-09-21  15:36:00
37       4    35  2024-09-21  15:37:00
38       4    38  2024-09-21  15:38:00
39       4    36  2024-09-21  15:39:00
40       5    38  2024-09-21  15:30:00
41       5    37  2024-09-21  15:31:00
42       5    39  2024-09-21  15:32:00
43       5    41  2024-09-21  15:33:00
44       5    40  2024-09-21  15:34:00
45       5    42  2024-09-21  15:35:00
46       5    43  2024-09-21  15:36:00
47       5    44  2024-09-21  15:37:00
48       5    45  2024-09-21  15:38:00
49       5    46  2024-09-21  15:39:00